services:
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: central-laravel
    volumes:
      - .:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db       # Nombre del servicio del contenedor de postgres
      DB_PORT: 5432
      DB_DATABASE: central_db
      DB_USERNAME: admin
      DB_PASSWORD: admin123
      TRAZABILIDAD_API_URL: http://trazabilidad.dasalas.shop/api
      ORGTRACK_API_URL: https://orgtrack.dasalas.shop/api
    depends_on:
      - db
    networks:
      - central-net
  nginx:
    image: nginx:latest
    container_name: central
    # expose:
    #   - "80"
    ports:
      - "8080:80" #---> despliegue local con puerto 8080
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - central-net
      - internal-network
      - proxy-network
  db:
    image: postgres:latest
    container_name: central-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: central_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - db-data:/var/lib/postgresql
    networks:
      - central-net

networks:
  central-net:
    driver: bridge
  internal-network:
    external: true
  proxy-network:
    external: true

volumes:
  db-data: