services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: centralhub-app
    container_name: centralhub-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - centralhub-network
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: centralhub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: centralhub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - db-data:/var/lib/postgresql/data
    networks:
      - centralhub-network
    ports:
      - "5432:5432"

networks:
  centralhub-network:
    driver: bridge

volumes:
  db-data:
